### ISSUE TITLE
Screenshot/screen sharing detection

### ISSUE THREAD

**Issue by BurkusCat** [FabriBertani/Plugin.Maui.ScreenSecurity#1]
I had a thought that could potentially be applicable to this plugin. Instead of preventing screenshots/recording, could it be possible to detect when a user has taken such actions? On iOS, preventing screenshots/recording is quite difficult, but is detection comparatively easier? What about Android?

Being able to detect screenshots/recording and issue a warning to users (or notify the backend system if it's a very serious application that users should not be screenshotting) may be more effective.  If users are blocked from taking screenshots, there are still ways to bypass the restriction (e.g. using another device to capture the screen).  However, if users receive a warning about violating the terms of service, it may discourage them more effectively.

I thought I'd start a discussion on this topic :)

**Comment by FabriBertani** [comment]
@BurkusCat is definitely a very good idea.

Maybe I can add some methods that only raise events when a screenshot or recording happens so the users will subscribe to this event on the MAUI app and delegate themselves what seems right to do in that situation.

On the bright side, on iOS it's easy to implement something like this, Android on the other hand it's a little bit more tricky and might require some workaround, add to that that Maui Android doesn't expose all the native methods.

I'll leave this issue open to discussion.

**Comment by JuanFcoMiranda** [comment]
Hi, on Android 14 we'll have this new approach to detect screenshots:

[https://developer.android.com/about/versions/14/features/screenshot-detection](https://developer.android.com/about/versions/14/features/screenshot-detection)

**Comment by FabriBertani** [comment]
Hi @JuanFcoMiranda, thank you for your contribution!

As soon as Google officially release Android 14 and Maui embrace the SDK (currently not available) I will definitely try to add this new approach.

**Comment by FabriBertani** [comment]
Hi everyone, I've added a new event handler `ScreenCaptured` to detect when a screenshot or a screen recording was taken. Please feel free to check the latest version `v1.2.0`
