### ISSUE TITLE
Add net6.0/net7.0 targets

### ISSUE THREAD

**Issue by tranb3r** [FabriBertani/Plugin.Maui.ScreenSecurity#15]
The architecture of my app looks like this: maui app (android/ios) -> UI library -> Core library
- maui app project holds the platform specific code (required to start the app)
- UI library holds the UI code (pages, views)
- Core library holds the business logic code (view models, services, models...)

Now that this plugin has a unified API, I'd like to call it from my Core library, which is pure net7.0.
However, the current build targets of this plugin only allows it to be called from platform specific code.

So, could you please add net6.0/net7.0 targets?

Thanks

**Comment by FabriBertani** [comment]
Hi @tranb3r, maybe I will consider it for the next release, among other things.

Just out of curiosity, did you share your UI and core projects with some other projects? If not, then I don't understand why you don't use the standard Maui project organization, you can totally have the business logic and the UI separated within the same Maui project now.

**Comment by tranb3r** [comment]
For many reasons:
- this design is inherited from a xamarin forms application
- it's a big app, so it makes sense to split the code in several assemblies
- this architecture enforces good practices: I'm sure the UI and the business logic stuff are not mixed
- when I modify the business logic or the UI, I don't want to rebuild the whole app
- I'm obfuscating the core dll, not the whole app
- the core assembly is unit-tested, and it's easier to do when it's separated from the app project

**Comment by FabriBertani** [comment]
Hi @tranb3r, after careful consideration, I decided to not move forward with this issue. This plugin is dependent on .Net MAUI and for that reason, it targets `net6/7.0-android`, `net6/7.0-ios` and `net6/7.0-windows`.

I highly recommend you create an implementation of this plugin on your MAUI project and use an `interface` via dependency injection into your `Core` project in order to use it correctly.

Best regards.

**Comment by tranb3r** [comment]
@FabriBertani 
I respect your choice.
However, could you please explain a bit more your decision?
Most MAUI plugins support net6.0 or netstandard2.0, allowing them to be installed in a pure cross-platform project. To name just a few: CommunityToolkit.Maui, Plugin.Firebase, Plugin.Fingerprint, Plugin.InAppBilling, Sharpnado.Tabs.Maui...
So, what is specific to Plugin.Maui.ScreenSecurity, that would prevent you from doing it?

**Comment by FabriBertani** [comment]
@tranb3r I made some time in my schedule and added net6 and net7 targets.
Will be available in the next release.

`netstandard` will not be supported.
`Xamarin.Forms` will not be supported due to we are close to EOL.
