### ISSUE TITLE
iOS 17.0.3 not working

### ISSUE THREAD

**Issue by ea543** [FabriBertani/Plugin.Maui.ScreenSecurity#18]
as Title~,please~

iOS 17 not support?!

**Comment by freakmacleod** [comment]
I have also confirmed that in iOS 17 this plugin does not work anymore. Something in that iOS release bugged the screenshot function. Blur on MultiTask and Blur on Screenrecording still works but not the Screenshot option.

**Comment by pedroleon** [comment]
Yep, same issue here only with screenshot. Tested with iOS17 + NET8 .

**Comment by FabriBertani** [comment]
**Hi, a quick update on this issue**:

I've tried to debug this on my phone but unfortunately, it doesn't support iOS 17 and I'm currently in the process of moving abroad, so I don't have enough time to dedicate to it. In the meantime, I will try to get a phone with iOS 17 and run some tests to fix this issue.

Sorry for the inconvenience or delay this may be causing you.

P.S.: If you have an idea or workaround to this issue, PRs are appreciated and welcomed 😁

**Comment by ea543** [comment]
> **Hi, a quick update on this issue**:
> 
> I've tried to debug this on my phone but unfortunately, it doesn't support iOS 17 and I'm currently in the process of moving abroad, so I don't have enough time to dedicate to it. In the meantime, I will try to get a phone with iOS 17 and run some tests to fix this issue.
> 
> Sorry for the inconvenience or delay this may be causing you.
> 
> P.S.: If you have an idea or workaround to this issue, PRs are appreciated and welcomed 😁

wow~Thanks~ Looking forward to good news~

**Comment by FabriBertani** [comment]
Fixed by PR [#22](https://github.com/FabriBertani/Plugin.Maui.ScreenSecurity/pull/22)

**Comment by denhaandrei** [comment]
Unfortunately, fix does not work in my cases(
https://github.com/FabriBertani/Plugin.Maui.ScreenSecurity/issues/27
