### ISSUE TITLE
Not Working for Windows

### ISSUE THREAD

**Issue by zaibchahal** [FabriBertani/Plugin.Maui.ScreenSecurity#20]
![image](https://github.com/FabriBertani/Plugin.Maui.ScreenSecurity/assets/82075049/f3b65d4a-ffb2-453e-9c0b-421b828bad15)

**Comment by zaibchahal** [comment]
I am using it in MAUI Blazor and I only want to prevent main page.
But it is not preventing screenshot or screen recording

**Comment by FabriBertani** [comment]
Hey @zaibchahal, I have a few questions:
- Which Net version are you using on your project (Net6, Net7 or Net8)?
- Which version of Windows are you running?
- Is there any error in the prompt?

This will help me to look in the right direction.

**Comment by FabriBertani** [comment]
Hi @zaibchahal, hope you're doing well.

Please check the latest version of the plugin (currently `1.1.8-beta`) and also check the new Blazor sample on the samples forlder.

Let me know if that work for you.

**Comment by FabriBertani** [comment]
Closed due to inactivity and lack of response from the author.
