### ISSUE TITLE
iOS 17 screen blur but screenshots allowed - not fixed after update to 1.1.6

### ISSUE THREAD

**Issue by denhaandrei** [FabriBertani/Plugin.Maui.ScreenSecurity#27]
See details:
https://github.com/denhaandrei/iOSDisableScreenshot

```
        public AppShell()
        {
            InitializeComponent();
            Navigating += Current_Navigating;
            Navigated += AppShell_Navigated;
        }

        private static bool isSecure = false;
        private void Current_Navigating(object sender, ShellNavigatingEventArgs e)
        {
            var str = e.Target.Location.OriginalString;
            if (!isSecure && isSecurityPage(str))
            {
                isSecure = true;
                ScreenSecurity.Default.ActivateScreenSecurityProtection(true, true, true);
            }
        }

        private void AppShell_Navigated(object sender, ShellNavigatedEventArgs e)
        {
            var currentPath = GetCurrentPath();

            if (isSecure && !string.IsNullOrWhiteSpace(currentPath) &&
                !isSecurityPage(currentPath))
            {
                isSecure = false;
                ScreenSecurity.Default.DeactivateScreenSecurityProtection();
            }
        }

        private bool isSecurityPage(string currentPath)
        {
            return currentPath.EndsWith(nameof(DScreenshot));
        }
```

AppShell:
Current_Navigating - disable screenshots on some pages
AppShell_Navigated - enable screenshots

Blur works as expected but screenshots are always allowed on iOS 17

Details:
```
Xamarin.PreBuilt.iOS[2423:1841789] Exception Stacktrace:    at Foundation.NSObject.InitializeHandle(NativeHandle handle, String initSelector) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:line 661
Xamarin.PreBuilt.iOS[2423:1841789]    at UIKit.UIImage..ctor(String filename) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIImage.g.cs:line 106
   at Plugin.Maui.ScreenSecurity.Platforms.iOS.ScreenshotProtectionManager.<>c__DisplayClass4_0.<SetScreenshotProtection>b__0()

Xamarin.PreBuilt.iOS[2423:1841789] SetScreenshotProtection failed with Exception message: Could not initialize an instance of the type 'UIKit.UIImage': the native 'initWithContentsOfFile:' method returned nil.
Xamarin.PreBuilt.iOS[2423:1841789] It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
```

**Comment by denhaandrei** [comment]
After some investigation, I tried to update the package multiple times/remove the bin, and obj folders/use the package as source code/redownload the solution from scratch/add and remove images related to this functionality. The issue was fixed. 
So as I see Visual Studio cached some data. 
This package 1.1.6 now works as expected!

Now it works fine, but I can`t find a concrete reason why it did not work previously in my solution and in the empty solution attached to the issue.

P.S. Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.8.6

**Comment by denhaandrei** [comment]
The issue comes back after clear the bin/obj folder and rebuild the solution.
To fix it I add two images manually to the folder and to the project:
		<MauiImage Include="Platforms\iOS\black_bg.png" />
		<MauiImage Include="Platforms\iOS\white_bg.png" />

So the bug still exists with 1.1.6 - images do not works in the NuGet package as expected

**Comment by Dokug** [comment]
For me, this is not working either.
In my debug output I noticed the following line, that might be of interest to you:
`Xamarin.PreBuilt.iOS[744:82359] SetScreenshotProtection failed with Exception message: Could not initialize an instance of the type 'UIKit.UIImage': the native 'initWithContentsOfFile:' method returned nil.`

The code I used to activate the screen protection was:
```
_screenSecurity.ActivateScreenSecurityProtection(new ScreenProtectionOptions
{
    PreventScreenRecording = true,
    PreventScreenshot = true,
});
```

**Comment by FabriBertani** [comment]
Will check this.

**Comment by ea543** [comment]
not working on iOS 17.4 after update 1.1.6~
Fighting~

> Will check this.

**Comment by jpmm94** [comment]
Any news about it?

**Comment by jpmm94** [comment]
> The issue comes back after clear the bin/obj folder and rebuild the solution. To fix it I add two images manually to the folder and to the project:
> 
> ```
> 		<MauiImage Include="Platforms\iOS\black_bg.png" />
> 		<MauiImage Include="Platforms\iOS\white_bg.png" />
> ```
> 
> So the bug still exists with 1.1.6 - images do not works in the NuGet package as expected
> 
> P.S. Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.9.3 still not working

This works for me

**Comment by ea543** [comment]
> black_bg

yes~thanks, works for me,too~

**Comment by FabriBertani** [comment]
Hello everybody.

I've uploaded a new pre-release version `1.1.7-beta` in which I applied a new implementation for this issue. Please, check it out and return some feedback here.

**Comment by Dokug** [comment]
Hi, I've tried it out, and the screen protection now seems to work, using a black/white texture.
For the purposes of preventing screenshots/recordings, this works fine for me, so from my side you are good to go 👍

Thanks for your work and for following up this issue!

**Comment by FabriBertani** [comment]
Thanks for the feedback @Dokug. I will close this issue with the new stable release, but there is room for improvement here, so I will continue testing some changes and improvements after that point 😃

**Comment by CalbinKing** [comment]
It's still now working on it even though I updated it in 1.1.7-beta

**Comment by CalbinKing** [comment]
> > The issue comes back after clear the bin/obj folder and rebuild the solution. To fix it I add two images manually to the folder and to the project:
> > ```
> > 		<MauiImage Include="Platforms\iOS\black_bg.png" />
> > 		<MauiImage Include="Platforms\iOS\white_bg.png" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So the bug still exists with 1.1.6 - images do not works in the NuGet package as expected
> > P.S. Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.9.3 still not working
> 
> This works for me

Where did you the those images?

**Comment by CalbinKing** [comment]
> It’s still not working for me, even after I updated to 1.1.7-beta.

In the emulator is not working but on actual device it works!

**Comment by ea543** [comment]
> > > The issue comes back after clear the bin/obj folder and rebuild the solution. To fix it I add two images manually to the folder and to the project:
> > > ```
> > > 		<MauiImage Include="Platforms\iOS\black_bg.png" />
> > > 		<MauiImage Include="Platforms\iOS\white_bg.png" />
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So the bug still exists with 1.1.6 - images do not works in the NuGet package as expected
> > > P.S. Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.9.3 still not working
> > 
> > 
> > This works for me
> 
> Where did you get those images?

Use Windows Paint or any paint and create it~

**Comment by nmano2188** [comment]
Facing difference issue. I'm using 1.1.7-beta.
Showing a black screen and blinking after opening the app from background. Tested on physical device version 17.5.1

**Comment by vitorelli** [comment]
@FabriBertani, I tested latest changes, they work pretty well on iOS (included 18) and Android (Included 35). Could you please publish 1.1.9-beta?

**Comment by FabriBertani** [comment]
@vitorelli Sorry guys, I picked a side job that took much of my spare time. I will release the new update next Monday.

**Comment by vitorelli** [comment]
@FabriBertani after publishing, I think this issue could be closed.

**Comment by ea543** [comment]
Perfect v1.2.0

I just test iOS15,16,17 and 18 is all OK and not need add white_bg.png and black_bg.png

Thanks
