### ISSUE TITLE
Not working with blazor MAUI (Android) ?

### ISSUE THREAD

**Issue by jetonpeche** [FabriBertani/Plugin.Maui.ScreenSecurity#28]
How can I use it with blazor MAUI on Android ?
Your example don't work with it

**Comment by jetonpeche** [comment]
EDIT:
I fund it,  I had to copy past 3 lines of source code in mainActivity.cs
In OnResume() and OnPause()

**Comment by FabriBertani** [comment]
Hi @jetonpeche how are you?

What happens with this issue? Is it closed?

**Comment by vikashhd** [comment]
@FabriBertani, library is not working with Blazor MAUI app. Neither for Android nor for ios. Kindly advise.

**Comment by FabriBertani** [comment]
@vikashhd @jetonpeche 

I've added a new Blazor sample project with the implementation of this plugin, please take a look and confirm if that works for you.

**Comment by jetonpeche** [comment]
hello !

Yes it work on android 14 latest
But windows IDK how can i try ^^

Thank you

**Comment by FabriBertani** [comment]
Hi @jetonpeche.

Thank you for your feedback.

> If possible, can you add color config like IOS ?
Unfortunately, it's not possible to add this to Android or Windows, because it's handled by the OS on these platforms.
