### ISSUE TITLE
Plugin is not working with IFRAME full screen

### ISSUE THREAD

**Issue by vikashhd** [FabriBertani/Plugin.Maui.ScreenSecurity#35]
Dear Sir,
Plugin is not working with IFRAME video in full screen mode.

**Comment by FabriBertani** [comment]
Please provide a full example of your issue and how you're implementing it.

Also, most of the cases implementation is handled by the OS, which neither I can change, nor Maui.

**Comment by vikashhd** [comment]
Hi Sir,
I am loading video using iframe. Also I need to allow users to watch video on full screen. When click on the Full screen button I think app OS is taking care about this and app control is closed. That's why user can take screenshot/ screen recording. 
Is there any way to force Full screen mode in App's boundary or any restriction can be imposed please suggest.

**Comment by FabriBertani** [comment]
@vikashhd please provide a minimal reproducible example of your issue.

**Comment by vikashhd** [comment]
@page "/pages/videos/{id}
<iframe width="100%" height="100%" src="@url?autoplay=true&loop=false&muted=false&preload=true"
loading="lazy" style="position:absolute; top:0; left: 0"
allow="accelerometer;gyroscope;autoplay;encrypted-media;fullscreen"></iframe> 


When we do full screen we can able to take screenshot. Can you please advise any way out.

**Comment by FabriBertani** [comment]
I'm sorry, but I can't do anything at the moment due to this is being handled by OS.

If you find any solution or workaround to this a PR will be very welcomed.
