### ISSUE TITLE
[iOS] Screenshot

### ISSUE THREAD

**Issue by EdwardMcFlurry** [FabriBertani/Plugin.Maui.ScreenSecurity#4]
Hello @FabriBertani 

Thanks for this handy tool however, it seems like this tool doesn't or cannot protect against the User taking a Screenshot as I have been able to take multiple Screenshots and I also looked at perhaps I missed something in a Code. I saw this tool on @jfversluis video on YouTube.

**Comment by FabriBertani** [comment]
Hi @EdwardMcFlurry, thank you for pointing me at the @jfversluis video, I didn't know he made one 😅

Regarding your issue, currently, there is no method on iOS to prevent screenshots, or at least not without using some tricky ways that might not work.
The best I can do for the next version is add an event handler that people could use to know when users take some screenshots.

**Comment by EdwardMcFlurry** [comment]
@FabriBertani please do so. It’s worth pointing out that even my actual Banking App has the same functionality as your plugin provides but still users can take Screenshots, although I wasn’t paying attention to it but I’ll definitely check their next release to see it they cracked the issue of Screenshots.

**Comment by FabriBertani** [comment]
Hey @EdwardMcFlurry. I've come up with this solution:

![ios_screenshot_protection](https://github.com/FabriBertani/Plugin.Maui.ScreenSecurity/assets/16881840/08d65bd5-9b77-4a7a-867f-f79f7497bdda)

Hope this fits your needs, it would be available on the next stable release.

**Comment by EdwardMcFlurry** [comment]
Hi @FabriBertani 

Sorry it took me this long but I've just updated the Plugin to 1.0.7-beta and unfortunately the Screenshot protection doesn't seem to work on my physical iPhone 6 and on Simulator.

This is the code for it on App.xaml.cs inside the contractor...

//Enable the Screen Security for iOS.
#if IOS
        ScreenSecurity.Default.EnableBlurScreenProtection(ThemeStyle.Light);
        ScreenSecurity.Default.EnableScreenshotProtection();
        ScreenSecurity.Default.EnableScreenRecordingProtection();
#endif

Is there something I'm not doing right on the code above or?

**Comment by EdwardMcFlurry** [comment]
Hi @FabriBertani 

Thank you for the response.

I've tested it by moving the code to the first page as it works 🕺🏻

I'll wait for the stable release of your Plugin.

However, have you noticed that a User can start the recording in this case on a physical iPhone and then launch the App with the Protections on but still able to record the entire screen? 🤷🏻‍♂️

Anyway, this is is fantastic needed tool so thank you. 👌
